version: '3.8'

services:
  frontend:
    build: .
    container_name: plant-finder-frontend
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  backend:
    build: .
    container_name: plant-finder-backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${BACKEND_PORT:-3001}
      - PLANT_AGENTS_API_TOKEN=${PLANT_AGENTS_API_TOKEN}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:server" 